version: '3.7'

services:
  u22-app-db:
    image: mysql:8.0
    container_name: u22-app-db
    restart: always
    command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_USER: yoshiji
      MYSQL_PASSWORD: hogehogesecret
    ports:
      - 3306:3306
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: u22-app-db
    links:
      - u22-app-db
    depends_on:
      - u22-app-db
    ports:
      - 8888:80